name: CI Pipeline

on:
  push:
    branches: [main, master]
    tags: ["v*"]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
      - ".vscode/**"
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
      - ".vscode/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run meta-tests
        run: make -f dev.mk meta-test

  package:
    name: Build Package (${{ matrix.sdk_version }})
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk_version: ["24.10.6", "25.12.3"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export Project Variables
        run: |
          grep '^PKG_NAME:=' Makefile | sed 's/:=/=/' >> $GITHUB_ENV
          echo "GIT_COMMIT=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build Package
        run: make -f dev.mk package SDK_VERSION=${{ matrix.sdk_version }}
        env:
          GIT_COMMIT: ${{ env.GIT_COMMIT }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKG_NAME }}-${{ matrix.sdk_version }}
          path: bin/packages/**/${{ env.PKG_NAME }}*
